name: Build and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: ./artifacts.txt

  approve:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'

    steps:
      - name: Wait for approval
        run: echo "Waiting for manual approval..."

  deploy:
    needs: approve
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: build-artifacts
          path: ./artifacts-downloaded.txt

      - name: Deploy to server
        run: |
          echo "Deploying..."
          cat ./artficat-downloaded.txt
