name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Add date to artifact file name
        run: |
          DATE=$(date +'%Y-%m-%d')
          mv artifact.txt artifact-$DATE.txt

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: artifact-*.txt
          retention-days: 60
