name: Build and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch: 

jobs:
  build:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: artifact.txt

  approve:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'

    steps:
      - name: Check user permissions
        uses: actions/github-script@v6
        with:
          script: |
            const allowedUsers = ['uzresk'];
            if (!allowedUsers.includes(context.actor)) {
              core.setFailed('User not authorized to run this workflow');
            }

      - name: Wait for approval
        run: echo "Waiting for manual approval..."

  deploy:
    needs: approve
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: .

      - name: Deploy to server
        run: |
          echo "Deploying..."
          cat artifact.txt
