name: Build and Deploy

on:
  workflow_dispatch: 

jobs:
  approve:
    runs-on: ubuntu-latest
    steps:
      - name: Check user permissions
        uses: actions/github-script@v6
        with:
          script: |
            const allowedUsers = ['uzresk'];
            if (!allowedUsers.includes(context.actor)) {
              core.setFailed('User not authorized to run this workflow');
            }

      - name: Wait for approval
        run: echo "Waiting for manual approval..."

  deploy:
    needs: approve
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifacts
        uses: dawidd6/action-download-artifact@v6
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: build.yml
          workflow_conclusion: success
          name: build-output
          path: .
      
      - name: Deploy to server
        run: |
          echo "Deploying..."
          cat artifact.txt
