name: Environment 

on:
  push:
    branches:
      - main
  workflow_dispatch: 

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
      - name: Auto-approve deployment
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/deployments/${{ github.event.deployment.id }}/statuses \
            -d '{"state":"success"}'
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: echo variables
        run: echo ${{ vars.URL }}

